services:
  - type: web
    name: doubt-resolution-backend
    env: docker
    plan: free
    # The build context should be the backend folder
    rootDir: ./backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_DRIVER
        value: org.postgresql.Driver
      - key: DB_DIALECT
        value: org.hibernate.dialect.PostgreSQLDialect
      - key: JWT_SECRET
        generateValue: true
